### ISSUE TITLE
How to make a svg image responsive?

### ISSUE THREAD

**Issue by jharrvis** [cody1213/twism#2]
I've create a custom map but the map isn't responsive, how to make the map image responsive?
Thanks. really appreciate your help.

**Comment by cody1213** [comment]
I have a map project coming up soon so I'll update it to be as responsive as possible soon. It's never going to work well on phones but someone made it responsive here awhile back: http://www.theglobalipcenter.com/ip-employs-innovation/
I usually replace it with a dropdown menu on phones. It's too hard to click Rhode Island.
-- Cody Brumfield CTO Whetstone Education +1 (844) 807-2011 ext 102
On Thu, Mar 17, 2016 at 20:44, jharrvis <notifications@github.com> wrote:
I've create a custom map but the map isn't responsive, how to make the map image responsive?
thanks.

**Comment by jharrvis** [comment]
Hi thanks Cody for your reply
I've a look at the code but it's really complicated for me to understand how to make it responsive.
can you point out how to make it, or can I just use bootstrap class to make it responsive?

**Comment by cody1213** [comment]
I modified the example here (which uses bootstrap) to be responsive:
http://dev.codybrumfield.com/jquery-plugins/twism/example.html

So, this is how the JavaScript looks now:

```
    $(document).ready(function() {
        $('#worldmap').twism("create",
        {
          height: '100%',
          width: '100%',
          map: "world",
          border: "red",
          individualCountrySettings: [{
            name: "cn",
            color: "red"
          }]
        }, function() {
          //callback function after map loads
          $('#worldmap').twism("setCountry", {
            name: "ca",
            color: "blue"
          });
          $('#worldmap svg').css({height:'100%',width:'100%'});
        });
      });
```
When the plugin is initiated, I'm setting the height and width to 100%. That actually sets the container height/width.  So, in the callback function, I'm using jQuery to set the height and width of the svg to 100% as well.

**Comment by jharrvis** [comment]
Hi Cody
sorry for delay respond, I've implemented your code and yes it's work
now the map is responsive.
thanks a lot and I really appreciate your help.
