### ISSUE TITLE
Doesn't work offline

### ISSUE THREAD

**Issue by VeeK727** [cody1213/twism#3]
I'm trying to run it offline as in running your example.html file in the browser but the map doesn't load. The error is 
`jquery-2.1.4.min.js:4 XMLHttpRequest cannot load file:///location/to/project/dist/maps/world-map.svg. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.`
Is it possible to avoid this?

**Comment by cody1213** [comment]
Unfortunately, Chrome doesn't allow cross-origin requests over the file: protocol. There's a number of solutions, though.  The simplest is just to use Firefox.  You can also just run a simple local test server.  The easiest one, if you're familiar with the command line, is probably Node's [http-server](https://github.com/indexzero/http-server). If you haven't installed Node, install it.  Then, open the command line and run:

`npm install -g http-server`

Then, you can navigate to any directory and type `http-server` and it'll serve that directory locally over the http protocol (which Chrome allows).  If you prefer Python to Node, you can run `python -m SimpleHTTPServer` and accomplish the same thing.  (That one is pre-installed on OSX but it looks like you're running Windows.)  

If you hate the command line, there's also programs like [XAMPP](http://www.apachefriends.org) that will create a local test server with a GUI on Windows.
