### ISSUE TITLE
Suggestion - Allow a name to popup on Hover

### ISSUE THREAD

**Issue by VeeK727** [cody1213/twism#4]
Great Plugin mate! I only wish I could get a tooltip or something that would read the name of the country. We could probably specify it like
```
...
individualCountrySettings: [
    {
    	name: "uk",
        tooltip: "United Kingdom",
    	color: "#faa61a",
    	border: "white",
    	borderWidth: 1
    }
}
...
```

**Comment by cody1213** [comment]
I thought about it but adding a <title> tag to the SVG <path> tag (to use browser tooltips like <a title="whatever") breaks the hover event option in some browsers.  I haven't tested this but you can probably use bootstrap tooltips. Just make sure to specify the container like:

````
$("#element").tooltip({
    'container': 'body'
});
````

If you don't specify the container, Bootstrap puts the tooltip in the element being hovered over (which doesn't work in SVGs).
